plugins:
  process_manager_enabled:
    client: true
    default: true
  process_manager_openai_api_key:
    client: false
    default: ''
  process_manager_overdue_days_default:
    client: true
    type: integer
    default: 3
    min: 0
  process_manager_ai_prompt_system:
    client: false
    default: ""
    type: string
  process_manager_ai_model:
    client: false
    type: enum
    default: gpt-4o-mini
    choices:
      - gpt-3.5-turbo
      - gpt-4o
      - gpt-4o-mini
      - gpt-4-turbo
      - gpt-4
  process_manager_charts_allowed_groups:
    client: false
    type: group_list
    default: ""
